PRODUCTION = {
    'Program': [['Declaration-list', '$']],
    'Declaration-list' : [['Declaration', 'Declaration-list'], ['EPSILON']],
    'Declaration' : [['Declaration-initial', 'Declaration-prime']],
    'Declaration-initial' :  [['Type-specifier', 'ID']],
    'Declaration-prime' : [['Fun-declaration-prime'], ['Var-declaration-prime']],
    'Var-declaration-prime' : [[';'], ['[', 'NUM', ']', ';']],
    'Fun-declaration-prime' :  [['(', 'Params', ')', 'Compound-stmt']],
    'Type-specifier' : [['int'], ['void']],
    'Params' : [['int', 'ID', 'Param-prime', 'Param-list'], ['void']],
    'Param-list' : [[',', 'Param', 'Param-list'], ['EPSILON']],
    'Param' : [['Declaration-initial', 'Param-prime']],
    'Param-prime' : [['[', ']'], ['EPSILON']],
    'Compound-stmt' : [['{', 'Declaration-list', 'Statement-list', '}']],
    'Statement-list' : [['Statement', 'Statement-list'], ['EPSILON']],
    'Statement' : [['Expression-stmt'], ['Compound-stmt'], ['Selection-stmt'], ['Iteration-stmt'], ['Return-stmt']],
    'Expression-stmt' : [['Expression', ';'], ['break', ';'], [';']],
    'Selection-stmt' : [['if', '(', 'Expression', ')', 'Statement', 'Else-stmt']],
    'Else-stmt' : [['endif'], ['else', 'Statement endif']],
    'Iteration-stmt' : [['repeatm', 'Statement', 'until', '(', 'Expression', ')']],
    'Return-stmt' : [['return', 'Return-stmt-prime']],
    'Return-stmt-prime' : [[';'], ['Expression,' ';']],
    'Expression' : [['Simple-expression-zegond'], ['ID', 'B']],
    'B' : [['=', 'Expression'], ['[', 'Expression', ']', 'H'], ['Simple-expression-prime']],
    'H' : [['=', 'Expression'], ['G', 'D', 'C']],
    'Simple-expression-zegond' : [['Additive-expression-zegond', 'C']],
    'Simple-expression-prime' : [['Additive-expression-prime', 'C']],
    'C' : [['Relop Additive-expression'], ['EPSILON']],
    'Relop' : [['<'], ['==']],
    'Additive-expression' : [['Term', 'D']],
    'Additive-expression-prime' : [['Term-prime', 'D']],
    'Additive-expression-zegond' : [['Term-zegond', 'D']],
    'D' : [['Addop', 'Term', 'D'], ['EPSILON']],
    'Addop' : [['+'], ['-']],
    'Term' : [['Factor', 'G']],
    'Term-prime' : [['Factor-prime', 'G']],
    'Term-zegond' : [['Factor-zegond', 'G']],
    'G' : [['*', 'Factor', 'G'], ['EPSILON']],
    'Factor' : [['(', 'Expression', ')'], ['ID', 'Var-call-prime'], ['NUM']],
    'Var-call-prime' : [['(', 'Args', ')'], ['Var-prime']],
    'Var-prime' : [['[', 'Expression', ']'], ['EPSILON']],
    'Factor-prime' : [['(', 'Args', ')'], ['EPSILON']],
    'Factor-zegond' : [['(', 'Expression', ')'], ['NUM']],
    'Args' : [['Arg-list'], ['EPSILON']],
    'Arg-list' : [['Expression', 'Arg-list-prime']],
    'Arg-list-prime' : [[',', 'Expression', 'Arg-list-prime'], ['EPSILON']]
}

FIRST = {
    'Program' : ['$', 'int'],
    'Declaration-list' : ['EPSILON', 'int'],
    'Declaration' : ['int'],
    'Declaration-initial' : ['int'],
    'Declaration-prime' : ['(', ';', '['],
    'Var-declaration-prime' : [';', '['],
    'Fun-declaration-prime' : ['('],
    'Type-specifier' : ['int'],
    'Type-sepcifier' : ['void'],
    'Params' : ['int', 'void'],
    'Param-list' : [',', 'EPSILON'],
    'Param' : ['int'],
    'Param-prime' : ['[', 'EPSILON'],
    'Compound-stmt' : ['{'],
    'Statement-list' : ['EPSILON', '{', 'break', ';', 'if', 'repeat', 'return', 'ID', '(', 'NUM'],
    'Statement' : ['{', 'break', ';', 'if', 'repeat', 'return', 'ID' ,'(', 'NUM'],
    'Expression-stmt' : ['break', ';', 'ID', '(', 'NUM'],
    'Selection-stmt' : ['if'],
    'Else-stmt' : ['endif', 'else'],
    'Iteration-stmt' : ['repeat'],
    'Return-stmt' : ['return'],
    'Return-stmt-prime' : [';', 'ID', '(', 'NUM'],
    'Expression' : ['ID', '(', 'NUM'],
    'B' : ['=', '[', '(', '*', '+', '-', '<', '==', 'EPSILON'],
    'H' : ['=', '*', 'EPSILON', '+', '-', '<', '=='],
    'Simple-expression-zegond' : ['(', 'NUM'],
    'Simple-expression-prime' : ['(', '*', '+', '-', '<', '==', 'EPSILON'],
    'C' : ['EPSILON', '<', '=='],
    'Relop' : ['<', '=='],
    'Additive-expression' : ['(', 'ID', 'NUM'],
    'Additive-expression-prime' : ['(', '*', '+', '-', 'EPSILON'],
    'Additive-expression-zegond' : ['(', 'NUM'],
    'D' : ['EPSILON', '+', '-'],
    'Addop' : ['+', '-'],
    'Term' : ['(', 'ID', 'NUM'],
    'Term-prime' : ['(', '*', 'EPSILON'],
    'Term-zegond' : ['(', 'NUM'],
    'G' : ['*', 'EPSILON'],
    'Factor': ['(', 'ID', 'NUM'],
    'Var-call-prime' : ['(', '[', 'EPSILON'],
    'Var-prime' : ['[', 'EPSILON'],
    'Factor-prime' : ['(', 'EPSILON'],
    'Factor-zegond' : ['(', 'NUM'],
    'Args' : ['EPSILON', 'ID', '(', 'NUM'],
    'Arg-list' : ['ID', '(', 'NUM'],
    'Arg-list-prime' : [',', 'EPSILON']
}

FOLLOW = {
    'Program' : [],
    'Declaration_list' : ['$', '{', 'break', ';', 'if', 'repeat', 'return', 'ID', '(', 'NUM', '}'],
    'Declaration' : ['int', '$', '{', 'break', ';', 'if', 'repeat', 'return', 'ID', '(', 'NUM', '}'],
    'Declaration_initial' : ['(', ';', '[', ',', ')'],
    'Declaration_prime' : ['int', '$', '{', 'break', ';', 'if', 'repeat', 'return', 'ID', '(', 'NUM', '}'],
    'Var_declaration_prime' : ['int', '$', '{', 'break', ';', 'if', 'repeat', 'return', 'ID', '(', 'NUM', '}'],
    'Fun_declaration_prime' : ['int', '$', '{', 'break', ';', 'if', 'repeat', 'return', 'ID', '(', 'NUM', '}'],
    'Type_specifier' : ['ID'],
    'Params' : [')'],
    'Param_list' : [')'],
    'Param' : [',', ')'],
    'Param_prime' : [',', ')'],
    'Compound_stmt' : ['int', '$', '{', 'break', ';', 'if', 'repeat', 'return', 'ID', '(', 'NUM', '}', 'endif', 'else', 'until'],
    'Statement_list' : ['}'],
    'Statement' : ['{', 'break', ';', 'if', 'repeat', 'return', 'ID', '(', 'NUM', '}', 'endif', 'else', 'until'],
    'Expression_stmt' : ['{', 'break', ';', 'if', 'repeat', 'return', 'ID', '(', 'NUM', '}','endif', 'else', 'until'],
    'Selection_stmt' : ['{', 'break', ';', 'if', 'repeat', 'return', 'ID', '(', 'NUM', '}', 'endif', 'else', 'until'],
    'Else_stmt' : ['{', 'break', ';', 'if', 'repeat', 'return', 'ID', '(', 'NUM', '}', 'endif', 'else', 'until'],
    'Iteration_stmt' : ['{', 'break', ';', 'if', 'repeat', 'return', 'ID', '(', 'NUM', '}', 'endif', 'else', 'until'],
    'Return_stmt' : ['{', 'break', ';', 'if', 'repeat', 'return', 'ID', '(', 'NUM', '}', 'endif', 'else', 'until'],
    'Return_stmt_prime' : ['{', 'break', ';', 'if', 'repeat', 'return', 'ID', '(', 'NUM', '}', 'endif', 'else', 'until'],
    'Expression' : [';', ')', ']', ','],
    'B' : [';' ,')', ']', ','],
    'H' : [';', ')', ']', ','],
    'Simple_expression_zegond' : [';', ')', ']', ','],
    'Simple_expression_prime' : [';', ')', ']', ','],
    'C' : [';', ')', ']', ','],
    'Relop' : ['(', 'ID', 'NUM'],
    'Additive_expression' : [';', ')', ']', ','],
    'Additive_expression_prime' : ['<', '==', ';', ')', ']', ','],
    'Additive_expression_zegond' : ['<', '==', ';', ')', ']', ','],
    'D' : ['<', '==', ';', ')', ']', ','],
    'Addop' : ['(', 'ID', 'NUM'],
    'Term' : ['+', '-', ';', ')', '<', '==', ']', ','],
    'Term_prime' : ['+', '-', '<', '==', ';', ')', ']', ','],
    'Term_zegond' : ['+', '-', '<', '==', ';', ')', ']', ','],
    'G' : ['+', '-', '<', '==', ';', ')', ']', ','],
    'Factor' : ['*', '+', '-', ';', ')', '<', '==', ']', ','],
    'Var_call_prime' : ['*', '+', '-', ';', ')', '<', '==', ']', ','],
    'Var_prime' : ['*', '+', '-', ';', ')', '<', '==', ']', ','],
    'Factor_prime' : ['*', '+', '-', '<', '==', ';', ')', ']', ','],
    'Factor_zegond' : ['*', '+', '-', '<', '==', ';', ')', ']', ','],
    'Args' : [')'],
    'Arg_list' : [')'],
    'Arg_list_prime' : [')']
}